declare {
   f();
   (int, float, string) = func1(string a, float c, float k, float r);
   (int, string) = func2(int, float, int, string);
   A;
   BTypeObjForDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDaysDaysAndDaysAndDays;
   int a = 2;
   const int d = 4+9*8;
   const float g = 4.2+9.1*8.6;
}
function start() {}